### ISSUE TITLE
Heroku Compatibility

### ISSUE THREAD

**Issue by Catarax** [rfinquiron/nodePHPchat#1]
Hello,

Unfortunately, the script is not compatible with Heroku.

When I edit the socket to (in nodeClient.js) :
var socket = io.connect(window.location.hostname);

It returns the error:
GET http://obscure-reaches-6033.herokuapp.com/socket.io/1/?t=1449749285012 404 (Not Found)

Thanks for the help!

**Comment by pendex900x** [comment]
Could you solve the problem after these 2 years? Or opted for another alternative?
